package com.fastcampus.kafkahandson.ugc.postsearch;

import com.fastcampus.kafkahandson.ugc.inspectedpost.model.InspectedPost;
import com.fastcampus.kafkahandson.ugc.port.PostSearchPort;
import com.fastcampus.kafkahandson.ugc.post.model.Post;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;

@Component
@RequiredArgsConstructor
public class PostSearchAdapter implements PostSearchPort {
    private final PostSearchRepository postSearchRepository;

    @Override
    public void indexPost(InspectedPost inspectedPost) {
        postSearchRepository.save(this.toDocument(inspectedPost));
    }

    @Override
    public void deletePost(Long id) {
        postSearchRepository.deleteById(id);
    }

    private PostDocument toDocument(InspectedPost inspectedPost) {
        Post post = inspectedPost.getPost();
        return new PostDocument(
                post.getId(),
                post.getTitle(),
                post.getContent(),
                inspectedPost.getCategoryName(),
                inspectedPost.getAutoGeneratedTags(),
                LocalDateTime.now()
        );
    }
}
